name: sakura-paper-plugin
version: '${version}'
main: org.sakura.plugin.sakurapaperplugin.SakuraPaperPlugin
api-version: '1.20'
author: 墨枫逸尘
libraries:
  - com.squareup.okhttp3:okhttp:4.12.0
  - com.google.code.gson:gson:2.9.1
  - io.github.cdimascio:dotenv-java:3.0.0